# Mcol to delta -----------------------------------------------------------
#' Retrieve the assortativity coeffcient from Mcol
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param Mcol A matrix representing the probabilities that an infector from a particular group (column) transmits the infection to every group (row).
#' @return A list with the delta coefficients for each group.
#' @seealso \code{\link{generate_Mcol}}
#' @export
#' @examples
#' Mcol <- generate_Mcol(
#'   n_groups = 2,
#'   size = c(50, 100),
#'   name = c("A", "B"),
#'   delta = c(2, 5.3))
#'
#' Mcol_to_delta(
#'   n_groups = 2,
#'   size = c(50, 100),
#'   name = c("A", "B"),
#'   Mcol = Mcol)
#'


Mcol_to_delta <- function(n_groups ,
                          size,
                          name,
                          Mcol) {
  # Generate Matrix under homogeneous mixing
  homo_mat <- generate_Mcol(
    n_groups = n_groups,
    size = size,
    name = name,
    delta = 1
  )


  # Equation
  Mcol_to_delta <- function(delta, group, homo_mat, Mcol) {
    (delta * homo_mat[group, group]) /
      ((delta * homo_mat[group, group]) + sum(homo_mat[colnames(homo_mat) != group, group])) - Mcol[group, group]
  }

  # retrieve delta by optimization for all groups
  optim_delta <- function(group, homo_mat, Mcol) {
    stats::optimize(function(x)
      abs(
        Mcol_to_delta(
          x,
          group = group,
          homo_mat = homo_mat,
          Mcol = Mcol
        )
      ),
      lower = -1e10,
      upper = 1e10)$minimum

  }

  # Loop for every group
  deltas <-
    purrr::map(.x = name, ~ optim_delta(group = .x, homo_mat , Mcol))
  names(deltas) <- name

  return(deltas)
}



#' # M0 to delta -----------------------------------------------------------
#' #' Retrieve the assortativity coeffcient from M0
#' #'
#' #' @param n_groups Number of groups
#' #' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' #' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' #'  @param r0 A numeric vector of length \code{n_groups} containing the basic Reproduction Number (R0) of the groups
#' #' @param M0 a matrix representing the number of secondary cases generated by an infector from a particular group (column) in a totally susceptible population in each other group (row).
#' #' @return A list with the delta coefficients for each group
#' #' @seealso \code{\link{generate_Mcol}}
#' #' @export
#' #' @examples
#' #' M0 <- generate_M0(
#' #'   n_groups = 2,
#' #'   size = c(50, 100),
#' #'   name = c("A", "B"),
#' #'   r0 = c(5, 3),
#' #'   delta = c(2, 5.3))
#' #'
#' #' M0_to_delta(
#' #'   n_groups = 2,
#' #'   size = c(50, 100),
#' #'   name = c("A", "B"),
#' #'   r0 = c(5, 3),
#' #'   M0 = M0)
#' #'
#'
#' M0_to_delta <- function(n_groups ,
#'                         size,
#'                         name,
#'                         r0,
#'                         M0) {
#'   # Generate Matrix under homogeneous mixing
#'   homo_mat <- generate_M0(
#'     n_groups = n_groups,
#'     size = size,
#'     name = name,
#'     r0 = r0,
#'     delta = 1
#'   )
#'
#'   # Equation
#'   M0_to_delta <- function(delta, group, r0, homo_mat, M0) {
#'     names(r0) <- group
#'
#'     (r0[[group]] * ((delta * homo_mat[group, group]) /
#'                       ((
#'                         delta * homo_mat[group, group]
#'                       ) + sum(homo_mat[colnames(homo_mat) != group, group])))) - M0[group, group]
#'   }
#'
#'   # retrieve delta by optimization for all groups
#'   optim_delta <- function(group, r0, homo_mat, M0) {
#'     stats::optimize(function(x)
#'       abs(
#'         M0_to_delta(
#'           x,
#'           group = group,
#'           r0 = r0,
#'           homo_mat = homo_mat,
#'           M0 = M0
#'         )
#'       ),
#'       lower = -1e10,
#'       upper = 1e10)$minimum
#'
#'   }
#'
#'   # Loop for every group
#'   deltas <-
#'     purrr::map(.x = name, ~ optim_delta(group = .x, r0, homo_mat , M0))
#'   names(deltas) <- name
#'
#'   return(deltas)
#' }
