#' Compute Binomial Mixing Matrix
#'
#' Computes a binomial mixing matrix from data based on the specified time window.
#' Provides the estimate and 95% CI for the within group mixing frequency.
#'
#' @param data The input data frame containing the source_group and group columns.
#' @param min_t The minimum time for the window.
#' @param max_t The maximum time for the window.
#'
#' @return A matrix representing the binomial mixing matrix with estimates, confidence intervals, successes (within group transmission), and trials (total no of transmission).
#'
#' @importFrom stats binom.test
#' @export

binom_mix <- function(data, min_t, max_t) {
  #Filter data: bias in backward GT!
  df <-
    subset(
      data,
      date_onset >= min_t &
        date_onset <= max_t &
        !is.na(source),
      select = c(source_group, group)
    )

  if (nrow(df) < 1) {
    #return empty matrix
    mixMat <- matrix(NA,
                     nrow = 1,
                     ncol = 5,
                     dimnames = list(
                       NULL,
                       c("est", "lower_ci", "upper_ci", "successes", "trials")
                     ))
    mixMat[] <- c(NA, NA, NA, 0, 0)
    row.names(mixMat) <- NA
    return(mixMat)
  }

  #Count pairs
  counts <- t(table(df$source_group, df$group))

  # Check for missing rows (no cases generated by a col)
  missing_rows <- setdiff(colnames(counts), rownames(counts))
  if (length(missing_rows) > 0) {
    counts <-
      rbind(counts,
            matrix(
              0,
              nrow = length(missing_rows),
              ncol = ncol(counts),
              dimnames = list(missing_rows, colnames(counts))
            ))
  }

  mixMat <- matrix(
    nrow = ncol(counts),
    ncol = 5,
    dimnames = list(
      colnames(counts),
      c("est", "lower_ci", "upper_ci", "successes", "trials")
    )
  )

  for (i in 1:ncol(counts)) {
    binom_result <- stats::binom.test(x = counts[i, i],
                                      n = sum(counts[, i]))
    est <- binom_result$estimate[[1]]
    lower_ci <- binom_result$conf.int[1]
    upper_ci <- binom_result$conf.int[2]
    successes <- binom_result$statistic[[1]]
    trials <- binom_result$parameter[[1]]
    mixMat[i, ] <- c(est, lower_ci, upper_ci, successes, trials)
  }

  return(mixMat)
}

