# MCOL: A matrix that represents the probability of an infector from a particular group (column) transmitting the infection to every group (row). It accounts for the receiving group size & the assortativity coefficient (delta).
# M0: A matrix that represents the number of secondary cases generated by an infector from a particular group (column) in a totally susceptible population in each other group (row), taking into the receiving group size, the assortativity coefficient and the infector's R0.
# Mt: A matrix that represents the number of secondary cases generated by an infector from a particular group (column) in a partially infected population at time t in each other group (row), taking into the receiving group size, the assortativity coefficient, the infector's R0 and the proportion of susceptibles in each receiving group.


# MCOL --------------------------------------------------------------------
#' Generate Mcol matrix
#'
#' Generates a matrix representing the probability of an infector from a particular group (column) transmitting the infection to every group (row). It accounts for the receiving group size & the assortativity coefficient (delta).
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param delta A numeric vector of length \code{n_groups} containing the assortativity coefficient for each group (default is 1 for all groups)
#' @return A matrix representing the number of secondary cases generated by an infector from a particular group (column) in a totally susceptible population in each other group (row), taking into the receiving group size and the assortativity coefficient.
#' @export
#' @examples
#' generate_Mcol(
#'   n_groups = 2,
#'   name = c("A", "B"),
#'   size = c(100, 100),
#'   delta = c(2, 2)
#' )
#'
generate_Mcol <-
  function(n_groups,
           name = NULL,
           size,
           delta = rep(1, n_groups)
           ) {
    if (is.null(name)) {
      name <- LETTERS[1:n_groups]
    }

    size_prop <- size / sum(size)

    Mcol <- matrix(
      rep(size_prop, each = n_groups),
      nrow = n_groups,
      ncol = n_groups,
      dimnames = list(c(name),
                      c(name)),
      byrow = TRUE
    )

    # Multiply diagonal elements by delta
    diag(Mcol) <- diag(Mcol) * delta

    # Normalize columns
    Mcol <- sweep(Mcol, 2, colSums(Mcol), `/`)

    return(Mcol)
  }



# M0 ----------------------------------------------------------------------
#' Generate M0 matrix
#'
#' Generates a matrix representing the number of secondary cases generated by an infector from a particular group (column) in a totally susceptible population in each other group (row), taking into the receiving group size, the assortativity coefficient and the infector's R0.
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param r0 A numeric vector of length \code{n_groups} containing the basic reproductive number of the disease in each group
#' @param delta A numeric vector of length \code{n_groups} containing the assortativity coefficient for each group (default is 1 for all groups)
#' @return A matrix representing the number of secondary cases generated by an infector from a particular group (column) in a totally susceptible population in each other group (row), taking into the receiving group size, the assortativity coefficient and the infector's R0.
#' @seealso \code{\link{generate_Mcol}}
#' @export
#' @examples
#' generate_M0(
#'   n_groups = 2,
#'   name = c("A", "B"),
#'   size = c(100, 100),
#'   r0 = c(5, 2.5),
#'   delta = c(2, 2)
#' )

generate_M0 <-
  function(n_groups,
           name = NULL,
           size,
           r0,
           delta = rep(1, n_groups)) {

    Mcol <- generate_Mcol(n_groups = n_groups,
                          name = name,
                          size = size,
                          delta = delta)

    # Multiply columns by r0
    M0 <- sweep(Mcol, 2, r0, `*`) #M0 <- Mcol %*% diag(r0)

    colnames(M0) <- name

    return(M0)
  }


# Mt  ----------------------------------------------------------------------
#' Generate Mt matrix
#'
#' Generates a matrix representing the number of secondary cases generated by an infector from a particular group (column) in each other group (row) at time t, taking into the receiving group size, the assortativity coefficient, the infector's R0 and the target group proportion of susceptible.
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param r0 A numeric vector of length \code{n_groups} containing the basic reproductive number of the disease in each group
#' @param prop_susceptible A numeric vector of length \code{n_groups} containing the proportion of susceptible in each group (between 0 and 1)
#' @param delta A numeric vector of length \code{n_groups} containing the assortativity coefficient for each group (default is 1 for all groups)
#' @return A matrix representing the number of secondary cases generated by an infector from a particular group (column) in a totally susceptible population in each other group (row), taking into the receiving group size, the assortativity coefficient and the infector's R0 and the target group proportion of susceptible..
#' @seealso \code{\link{generate_M0}}
#' @export
#' @examples
#' generate_Mt(
#'   n_groups = 2,
#'   name = c("A", "B"),
#'   size = c(100, 100),
#'   r0 = c(5, 2.5),
#'   prop_susceptible = c(0.5, 0.95),
#'   delta = c(2, 2)
#' )
generate_Mt <-
  function(n_groups,
           name = NULL,
           size,
           r0,
           prop_susceptible,
           delta = rep(1, n_groups)) {

   M0 <- generate_M0(
      n_groups = n_groups,
      name = name,
      size = size,
      r0 = r0,
      delta = delta
    )

    # Multiply rows by proportion of susceptible
    Mt <- sweep(M0, 1, prop_susceptible, `*`)

    return(Mt)
  }



# Mcolt  ----------------------------------------------------------------------
#' Generate Mcolt matrix
#'
#' Generates a matrix representing the proportion of infection going from one group to another accounting for the groups sizes, the assortativity coefficient, the infector's R0 and the proportion of susceptible.
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param r0 A numeric vector of length \code{n_groups} containing the basic reproductive number of the disease in each group
#' @param prop_susceptible A numeric vector of length \code{n_groups} containing the proportion of susceptible in each group (between 0 and 1)
#' @param delta A numeric vector of length \code{n_groups} containing the assortativity coefficient for each group (default is 1 for all groups)
#' @return A matrix representing the probability of transmission by an infector from a particular group (column) in a partially susceptible population in each other group (row), taking into the receiving group size, the assortativity coefficient, the infector's R0 and the receiving group proportion of suceptible.
#' @seealso \code{\link{generate_Mcol}}
#' @export
#' @examples
#' generate_Mcolt(
#'   n_groups = 2,
#'   name = c("A", "B"),
#'   size = c(100, 100),
#'   r0 = c(5, 2.5),
#'   prop_susceptible = c(0.5, 0.95),
#'   delta = c(2, 2)
#' )
#'
generate_Mcolt <-
  function(n_groups,
           name = NULL,
           size,
           r0,
           prop_susceptible,
           delta = rep(1, n_groups)) {

    Mt <- generate_Mt(
      n_groups = n_groups,
      name = name,
      size = size,
      r0 = r0,
      prop_susceptible = prop_susceptible,
      delta = delta
    )

    # Divide columns by Rt
    Mcolt <- sweep(Mt, 2, colSums(Mt), `/`)

    return(Mcolt)
  }



#Mcol describes the probability of transmission from one group to another, while M0 describes the expected number of secondary infections within each group, given that an individual is infected.
