# Mcol to delta -----------------------------------------------------------
#' Retrieve the assortativity coefficient from the mixing matrix 'Mcol'
#'
#' The mixing matrix Mcol is a matrix representing the proportions of
#' cases generated by an infector from a particular group (column) in a
#' totally susceptible population in each other group (row).
#'
#' Mcol_to_delta_optim can retrieve the assortativity coefficient `delta`
#' in the early phase of the epidemic.
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param Mcol_observed The mixing matrix
#' @return A vector with the delta coefficients for each group
#' @seealso \code{\link{generate_Mcol}}
#' @export
#' @examples
#'
#'
#' Mcol_observed <- generate_Mcol(
#'   n_groups = 2,
#'   size = c(50, 100),
#'   name = c("A", "B"),
#'   delta = c(2, 5.3))
#'
#' Mcol_to_delta_optim(
#'   n_groups = 2,
#'   size = c(50, 100),
#'   name = c("A", "B"),
#'   Mcol_observed = Mcol_observed)
#'



Mcol_to_delta_optim <-
  function(n_groups, name, size, Mcol_observed) {
    calculate_difference <- function(delta) {
      Mcol <-
        generate_Mcol(
          n_groups = n_groups,
          name = name,
          size = size,
          delta = delta
        )
      diff_matrix <- diag(Mcol) - diag(Mcol_observed)
      difference <- sum(diff_matrix ^ 2)
      return(difference)
    }


    opt_result <- optim(
      par = rep(1, n_groups),
      fn = calculate_difference,
      method = "L-BFGS",
      lower = rep(0, n_groups)
    )

    delta <- opt_result$par

    return(delta)
  }

# M0 to delta -----------------------------------------------------------
#' Retrieve the assortativity coefficient from the next generation matrix 'M0'
#'
#' The next generation matrix is a matrix representing the number of secondary
#' cases generated by an infector from a particular group (column) in a
#' totally susceptible population in each other group (row).
#'
#' M0_to_delta_optim can retrieve the assortativity coeffcient `delta`
#' in the early phase of the epidemic.
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param r0 A numeric vector of length \code{n_groups} containing the basic Reproduction Number (R0) of the groups
#' @param M0_observed The next generation matrix
#' @return A vector with the delta coefficients for each group
#' @seealso \code{\link{generate_M0}}
#' @export
#' @examples
#'
#'
#' M0_observed <- generate_M0(
#'   n_groups = 2,
#'   size = c(50, 100),
#'   name = c("A", "B"),
#'   r0 = c(5, 3),
#'   delta = c(2, 5.3))
#'
#' M0_to_delta_optim(
#'   n_groups = 2,
#'   size = c(50, 100),
#'   name = c("A", "B"),
#'   r0 = c(5, 3),
#'   M0_observed = M0_observed)
#'

M0_to_delta_optim <-
  function(n_groups, name, size, r0, M0_observed) {
    calculate_difference <- function(delta) {
      M0 <-
        generate_M0(
          n_groups = n_groups,
          name = name,
          size = size,
          r0 = r0,
          delta = delta
        )
      diff_matrix <- diag(M0) - diag(M0_observed)
      difference <- sum(diff_matrix ^ 2)
      return(difference)
    }


    opt_result <- optim(
      par = rep(1, n_groups),
      fn = calculate_difference,
      method = "L-BFGS",
      lower = rep(0, n_groups)
    )

    delta <- opt_result$par

    return(delta)
  }


# Mt to delta -----------------------------------------------------------
#' Retrieve the assortativity coefficient from the effective next generation matrix 'Mt'
#'
#' The effective next generation matrix refers to a matrix representing the
#' number of secondary cases generated by an infector from a particular group (column)
#' in each other group (row) at time t.
#'
#' Mt_to_delta_optim can retrieve the assortativity coefficient `delta`
#' at any phase of the epidemic.
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param r0 A numeric vector of length \code{n_groups} containing the basic Reproduction Number (R0) of the groups
#' @param prop_susceptible A numeric vector of length \code{n_groups} containing the proportion of susceptible in each group at time t
#' @param Mt_observed The effective next generation matrix
#' @return A vector with the delta coefficients for each group
#' @seealso \code{\link{generate_Mcol}}
#' @export
#' @examples
#'
#' n_groups = 2
#' size = c(1e4, 1e5)
#' name = LETTERS[1:n_groups]
#' r0 = c(5, 3)
#' prop_susceptible = c(0.6, 0.3)
#' delta = c(10, 2)
#'
#' Mt_observed <- generate_Mt(
#'   n_groups = n_groups,
#'   size = size,
#'   name = name,
#'   r0 = r0,
#'   prop_susceptible = prop_susceptible,
#'   delta = delta
#' )
#'
#' Mt_to_delta_optim(
#'   n_groups = n_groups,
#'   size = size,
#'   name = name,
#'   r0 = r0,
#'   prop_susceptible = prop_susceptible,
#'   Mt_observed = Mt_observed
#')
#'
Mt_to_delta_optim <-
  function(n_groups, name, size, r0, prop_susceptible, Mt_observed) {
    calculate_difference <- function(delta) {
      Mt <-
        generate_Mt(
          n_groups = n_groups,
          name = name,
          size = size,
          r0 = r0,
          prop_susceptible = prop_susceptible,
          delta = delta
        )
      diff_matrix <- diag(Mt) - diag(Mt_observed)
      difference <- sum(diff_matrix ^ 2)
      return(difference)
    }


    opt_result <- optim(
      par = rep(1, n_groups),
      fn = calculate_difference,
      method = "L-BFGS",
      lower = rep(0, n_groups)
    )

    delta <- opt_result$par

    return(delta)
  }



# Mcolt -------------------------------------------------------------------
#' Retrieve the assortativity coefficient from the effective mixing matrix 'Mcolt'
#'
#' The effective next generation matrix refers to a matrix representing the
#' number of secondary cases generated by an infector from a particular group (column)
#' in each other group (row) at time t.
#'
#' Mcolt_to_delta_optim can retrieve the assortativity coefficient `delta`
#' at any phase of the epidemic.
#'
#' @param n_groups Number of groups
#' @param name A character vector of length \code{n_groups} containing the names of the groups
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param r0 A numeric vector of length \code{n_groups} containing the basic Reproduction Number (R0) of the groups
#' @param prop_susceptible A numeric vector of length \code{n_groups} containing the proportion of susceptible in each group at time t
#' @param Mcolt_observed The effective next generation matrix
#' @return A vector with the delta coefficients for each group
#' @seealso \code{\link{generate_Mcol}}
#' @export
#' @examples
#'
#' n_groups = 2
#' size = c(1e4, 1e5)
#' name = LETTERS[1:n_groups]
#' r0 = c(5, 3)
#' prop_susceptible = c(0.6, 0.3)
#' delta = c(10, 2)
#'
#' Mcolt_observed <- generate_Mcolt(
#'   n_groups = n_groups,
#'   size = size,
#'   name = name,
#'   r0 = r0,
#'   prop_susceptible = prop_susceptible,
#'   delta = delta
#' )
#'
#' Mcolt_to_delta_optim(
#'   n_groups = n_groups,
#'   size = size,
#'   name = name,
#'   r0 = r0,
#'   prop_susceptible = prop_susceptible,
#'   Mcolt_observed = Mcolt_observed
#')
#'
Mcolt_to_delta_optim <-
  function(n_groups, name, size, r0, prop_susceptible, Mcolt_observed) {
    calculate_difference <- function(delta) {
      Mcolt <-
        generate_Mcolt(
          n_groups = n_groups,
          name = name,
          size = size,
          r0 = r0,
          prop_susceptible = prop_susceptible,
          delta = delta
        )
      diff_matrix <- diag(Mcolt) - diag(Mcolt_observed)
      difference <- sum(diff_matrix ^ 2)
      return(difference)
    }


    opt_result <- optim(
      par = rep(1, n_groups),
      fn = calculate_difference,
      method = "L-BFGS",
      lower = rep(0, n_groups)
    )

    delta <- opt_result$par

    return(delta)
  }


