# Mcol to delta -----------------------------------------------------------
#' Retrieve the assortativity coefficient from the mixing matrix 'Mcol'
#'
#' The mixing matrix Mcol is a matrix representing the proportions of
#' cases generated by an infector from a particular group (column) in a
#' totally susceptible population in each other group (row).
#'
#' Mcol_to_delta can retrieve the assortativity coefficient `delta`
#' in the early phase of the epidemic.
#'
#' @param n_groups Number of groups
#' @param name Optional. A character vector of length \code{n_groups} containing the names of the groups (default is A,B,C...)
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param Mcol_observed The mixing matrix
#' @return A vector with the delta coefficients for each group
#' @seealso \code{\link{generate_Mcol}}
#' @export
#' @examples
#' n_groups = 4
#' name =LETTERS[1:n_groups]
#' size = round(runif(n_groups, min = 10, max = 1e3))
#' delta = runif(n_groups, min = 0.01, max = 1e3)
#'
#' Mcol_observed <- generate_Mcol(n_groups, name, size, delta)
#' Mcol_to_delta( n_groups = n_groups, size = size, Mcol_observed = Mcol_observed)
#'

Mcol_to_delta <- function(n_groups,
                           name = NULL,
                           size,
                           Mcol_observed) {
  delta <- numeric()
  size_prop <- size / sum(size)

  for (i in seq_len(n_groups)) {
    numerator <- Mcol_observed[i, i] * sum(size_prop[-i])

    denominator <-
      size_prop[i] * (1 - Mcol_observed[i, i])

    delta_i <- numerator / denominator
    delta <- c(delta, delta_i)
  }

  if (!is.null(name)) {
    names(delta) <- name
  }

  return(delta)
}






# n_groups = 4
# name =LETTERS[1:n_groups]
# size = round(runif(n_groups, min = 10, max = 1e3))
# delta = runif(n_groups, min = 0.01, max = 1e3)
# delta
#
# Mcol_observed <- generate_Mcol(n_groups, name, size, delta)
#
# get_delta <- function(n_groups,
#                       size,
#                       Mcol_observed) {
#   delta <- numeric()
#   size_prop <- size / sum(size)
#   numerator <- 1
#
#   for (i in seq_len(n_groups)) {
#     denominator <-
#       sum(size_prop[-i]) * size_prop[i] * ((1 / Mcol_observed[i, i]) - 1)
#     delta_i <- numerator / denominator
#     delta <- c(delta, delta_i)
#   }
#   return(delta)
# }
#
#
# get_delta(
#   n_groups,
#   size,
#   Mcol_observed)
# delta




# Mt_to_delta -------------------------------------------------------------

#' Calculate Assortativity Coefficients from Observed Mt Matrix
#'
#' The Mt_to_delta function calculates the assortativity coefficients (`delta`) based on the observed matrix `Mt`.
#' The matrix `Mt` represents the number of secondary cases generated by an infector from a particular group (column) in each other group (row) at a specific time `t`.
#'
#' @param n_groups Number of groups
#' @param name Optional. A character vector of length \code{n_groups} containing the names of the groups.
#' @param size A numeric vector of length \code{n_groups} containing the sizes of the groups
#' @param r0 A numeric vector of length \code{n_groups} containing the basic reproductive number of the disease in each group
#' @param prop_susceptible A numeric vector of length \code{n_groups} containing the proportion of susceptibles in each group (between 0 and 1)
#' @param Mt_observed The observed Mt matrix
#' @return A vector with the calculated assortativity coefficients (`delta`) for each group
#' @examples
#' n_groups = 2
#' name = LETTERS[1:n_groups]
#' size = c(100, 100)
#' delta = c(11, 2.5)
#' r0 = c(4, 3)
#' prop_susceptible = c(0.1, 0.7)
#'Mt_observed <-
#'  generate_Mt(n_groups, name, size, r0, prop_susceptible, delta)

#'Mt_to_delta(
#'  n_groups = n_groups,
#'  name = name,
#'  size = size,
#'  r0 = r0,
#'  prop_susceptible = prop_susceptible,
#'  Mt_observed = Mt_observed
#')
#'
#'@export


Mt_to_delta <- function(n_groups,
                        name = NULL,
                        size,
                        r0,
                        prop_susceptible,
                        Mt_observed) {
  delta <- numeric()
  size_prop <- size / sum(size)
  Rt <- r0 * prop_susceptible


  for (i in seq_len(n_groups)) {

    numerator <- Mt_observed[i, i] * sum(size_prop[-i])

    denominator <-
      size_prop[i] * (Rt[i] - Mt_observed[i, i])

    delta_i <- numerator / denominator

    delta <- c(delta, delta_i)
  }

  if (!is.null(name)) {
    names(delta) <- name
  }

  return(delta)
}





# MColt_to_delta ----------------------------------------------------------
#
# Mcolt_to_delta <- function(n_groups,
#                         name = NULL,
#                         size,
#                         r0,
#                         prop_susceptible,
#                         Mcolt_observed) {
#   delta <- numeric()
#   size_prop <- size / sum(size)
#   Rt <- r0 * prop_susceptible
#
#
#   for (i in seq_len(n_groups)) {
#
#     numerator <- Mcolt_observed[i, i] * sum(size_prop[-i])
#
#     denominator <-
#       size_prop[i] * (1 - Mcolt_observed[i, i])
#
#     delta_i <- numerator / denominator
#
#     delta <- c(delta, delta_i)
#   }
#
#   if (!is.null(name)) {
#     names(delta) <- name
#   }
#
#   return(delta)
# }
#
#
# n_groups = 2
# name =LETTERS[1:n_groups]
# size = c(100, 100)
# delta = c(10, 2)
# r0 = c(3,3)
# prop_susceptible = c(1,0.2)
#
# Mcolt_observed <-
#   generate_Mcolt(n_groups, name, size, r0, prop_susceptible, delta)
# Mcolt_observed
#
# Mcolt_to_delta(n_groups = n_groups,
#                name = name,
#                size = size,
#                r0 = r0,
#                prop_susceptible = prop_susceptible,
#                Mcolt_observed = Mcolt_observed)
# delta
